{% if inputs.trace_exporter == 'AWS X-Ray' %}
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  awsxray:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ awsxray ]
{% endif %}
